org: ecvph
app: jam
service: products-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  environment:
    PRODUCTS_TABLE: ${self:service}-${sls:stage}-products
    PRODUCTS_BUCKET: ${self:service}-${sls:stage}-images
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          Resource:
            - !GetAtt ProductsTable.Arn
        # S3 permissions
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - !GetAtt ProductsImagesBucket.Arn
            - !Join ['', [!GetAtt ProductsImagesBucket.Arn, '/*']]


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createProduct:
    handler: handler.create_product
    events:
      - httpApi:
          path: /products
          method: post
  getProducts:
    handler: handler.get_products
    events:
      - httpApi:
          path: /products
          method: get

plugins:
  - serverless-python-requirements

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Name
            Value: ${self:service}-products-table
    ProductsImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PRODUCTS_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - '*'
              MaxAge: 3000
        Tags:
          - Key: Name
            Value: ${self:service}-images-bucket